language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

addons:
    apt:
        packages:
            - cmake

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./test_lib
    - ./test_macro
    - cd ..
    - cd examples
    - cd bridge
    - make
    - cd ..
    - cd rollercoaster
    - make