language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

addons:
    apt:
        packages:
            - cmake

script:
    - mkdir build
    - cd build
    - cmake ..
    - ./test_lib
    - ./test_macro